# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Notebook\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Notebook(object):
    def setupUi(self, Notebook):
        Notebook.setObjectName("Notebook")
        Notebook.setWindowIcon(QtGui.QIcon('picture\icon.png'))
        Notebook.setEnabled(True)
        Notebook.resize(800, 800)
        Notebook.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Notebook.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(Notebook)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        Notebook.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Notebook)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        Notebook.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Notebook)
        self.statusbar.setObjectName("statusbar")
        Notebook.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Notebook)
        self.action.setObjectName("action")
        self.action.setShortcut('Ctrl+N')
        self.action.setStatusTip('New File')

        self.action_2 = QtWidgets.QAction(Notebook)
        self.action_2.setObjectName("action_2")
        self.action_2.setShortcut('Ctrl+R')
        self.action_2.setStatusTip('Recording')

        
        self.action_3 = QtWidgets.QAction(Notebook)
        self.action_3.setObjectName("action_3")
        self.action_3.setShortcut('Ctrl+O')
        self.action_3.setStatusTip('Open new File')
        
        self.action_4 = QtWidgets.QAction(Notebook)
        self.action_4.setObjectName("action_4")
        self.action_4.setShortcut('Ctrl+S')
        self.action_4.setStatusTip('Save new File')
        
        self.action_5 = QtWidgets.QAction(Notebook)
        self.action_5.setObjectName("action_5")
        
        self.action_6 = QtWidgets.QAction(Notebook)
        self.action_6.setObjectName("action_6")
        
        self.action_8 = QtWidgets.QAction(Notebook)
        self.action_8.setObjectName("action_8")
        
        self.action_9 = QtWidgets.QAction(Notebook)
        self.action_9.setObjectName("action_9")
        
        self.action_10 = QtWidgets.QAction(Notebook)
        self.action_10.setObjectName("action_10")
        
        self.action_11 = QtWidgets.QAction(Notebook)
        self.action_11.setObjectName("action_11")
        
        self.action_13 = QtWidgets.QAction(Notebook)
        self.action_13.setObjectName("action_13")
        
        self.action_15 = QtWidgets.QAction(Notebook)
        self.action_15.setObjectName("action_15")

        self.action_12 = QtWidgets.QAction(Notebook)
        self.action_12.setObjectName("action_12")
        
        self.action_16 = QtWidgets.QAction(Notebook)
        self.action_16.setObjectName("action_16")
        
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_5)
        self.menu_2.addAction(self.action_6)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_8)
        self.menu_2.addAction(self.action_9)
        self.menu_2.addAction(self.action_10)
        self.menu_2.addAction(self.action_13)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_15)
        self.menu_3.addAction(self.action_16)
        self.menu_3.addAction(self.action_12)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(Notebook)
        QtCore.QMetaObject.connectSlotsByName(Notebook)

    def retranslateUi(self, Notebook):
        _translate = QtCore.QCoreApplication.translate
        Notebook.setWindowTitle(_translate("Notebook", "Notebook"))
        self.menu.setTitle(_translate("Notebook", "Файл"))
        self.menu_2.setTitle(_translate("Notebook", "Правка"))
        self.menu_3.setTitle(_translate("Notebook", "Формат"))
        self.menu_5.setTitle(_translate("Notebook", "Настройки"))
        self.action.setText(_translate("Notebook", "Новый файл"))
        self.action_2.setText(_translate("Notebook", "Звуковая запись"))
        self.action_3.setText(_translate("Notebook", "Открыть"))
        self.action_4.setText(_translate("Notebook", "Сохранить"))
        self.action_5.setText(_translate("Notebook", "Сохранить как"))
        self.action_6.setText(_translate("Notebook", "Отменить"))
        self.action_8.setText(_translate("Notebook", "Копировать"))
        self.action_9.setText(_translate("Notebook", "Вставить"))
        self.action_10.setText(_translate("Notebook", "Вырезать"))
        self.action_11.setText(_translate("Notebook", "Выделить текст"))
        self.action_13.setText(_translate("Notebook", "Удалить"))
        self.action_15.setText(_translate("Notebook", "Выделить все"))
        self.action_12.setText(_translate("Notebook", "Голос"))
        self.action_16.setText(_translate("Notebook", "Шрифт"))
